version: "3.1"


services:

  globotunes:
      image: "reg.fa-advise.net:2083/gt:v1.2"
      environment:
        - COMPOSER_MEMORY_LIMIT=-1
        - APP_TYPE
        - ENV=prod
        - PROD=yes
      depends_on:
        - mongo_master
        - rabbitmq
        - redis
      volumes:
          - /etc/fa-advise-license.txt:/var/www/license.txt
      network_mode: host
      ports:
          - 8000:8000

  mongo_master:
      image: mongo:3.4
      volumes:
        - mongo:/var/lib/mongo
        - ./mongo/mongod.conf:/etc/mongod.conf
      network_mode: host

  rabbitmq:
      image: rabbitmq:3.7.12
      network_mode: host

  redis:
      image: redis:5.0.3
      network_mode: host

volumes:
  mongo:
